lib_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  get '/users', to: 'users#index', as: 'users'
  post '/users', to: 'users#create'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/libraries', to: 'libraries#index', as: 'libraries'
  post '/libraries', to: 'libraries#create'
  get '/library/:id', to: 'libraries#show', as: 'library'
  get '/libraries/new', to: 'libraries#new', as: 'new_library'

  get '/users/:user_id/libraries', to: 'library_users#index', as: 'user_libraries'
  post '/libraries/:library_id/users', to: 'library_users#create', as: 'library_users'
end

lib_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lib_app/app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :users, through: :library_users
end

lib_app/app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

lib_app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :library_users, dependent: :destroy
  has_many :libraries, through: :library_users

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

lib_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

lib_app/app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def index
    @libraries = Library.all
  end

  def show
    @library = Library.find_by(id: params[:id])
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.create(library_params)
    redirect_to libraries_path
  end

  private
    def library_params
      params.require(:library).permit(:name, :floor_count, :floor_area)
    end

end

lib_app/app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @libraries = @user.libraries # so we type less in the view
  end

  def create
    @library = Library.find(params[:library_id])
    @library.users.push(current_user)  # no error handling currently

    redirect_to current_user
  end

end

lib_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in."
      redirect_to @user
    else
      flash[:error] = "The username doesn't match the password"
      flash[:error] = "Incorrect email or password."
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end

end

lib_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    user_id = params[:id]
    @user = User.find_by(id: user_id)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to user_path(user)
    else
      flash[:error] = user.errors.full_messages.join(",")
      redirect_to new_user_path
    end
  end

  def update
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

end

lib_app/app/helpers/application_helper.rb
module ApplicationHelper
end

lib_app/app/helpers/libraries_helper.rb
module LibrariesHelper
end

lib_app/app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

lib_app/app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logout
    @current_user = session[:user_id] = nil
  end
end

lib_app/app/helpers/users_helper.rb
module UsersHelper
end

lib_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Create Account", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>
    <% flash.each do |name, msg| %>
      <p>
        <small> <%= name.capitalize %>: <%= msg %> </small>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

lib_app/app/views/libraries/index.html.erb
<% @libraries.each do |library| %>
  <div>
    <h3><%= library.name %></h3>
    <% if current_user %>
      <%= button_to "Join", library_users_path(library) %>
    <% end %>
  </div>
  <br>
<% end %>

lib_app/app/views/libraries/new.html.erb
<%= form_for @library do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.number_field :floor_count, placeholder: "Floor Count" %>
  </div>
  <div>
    <%= f.number_field :floor_area, placeholder: "Floor Area" %>
  </div>
  <%= f.submit %>
<% end %>

lib_app/app/views/libraries/show.html.erb
<h1>Library Info</h1>
Name: <%= @library.name %> <br>
Number of floors: <%= @library.floor_count %> <br>
Floor Area: <%= @library.floor_area %>

lib_app/app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libraries.each do |lib| %>
    <li><%= lib.name %></li>
  <% end %>
</ul>

lib_app/app/views/users/index.html.erb
<h1>Welcome to the Users Index!</h1>

<div>
  There are currently <%= @users.count %> user(s) signed up!
</div>

lib_app/app/views/users/new.html.erb
<h1>Join our community!</h1>
<%= form_for @user do |f| %>
  <%= f.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  <%= f.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  <%= f.text_field :email, class:"form-control", placeholder:"Email Address" %>
  <%= f.password_field :password, class:"form-control", placeholder:"password" %>
  <%= f.submit "Save Your Info" %>
<% end %>

lib_app/app/views/users/show.html.erb
<h1>Welcome!</h1>
<p>You're logged in, <%= @user.first_name %></p>